version: '3.1'

services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: teste
      MYSQL_DATABASE: curso-api-rest-spring
      MYSQL_USER: admin
      MYSQL_PASSWORD: teste
    ports:
      - 3306:3306
    networks:
      - pgnetwork

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: teste
    ports:
      - 5000:80
    depends_on:
      - mysql
    networks:
      - pgnetwork

networks:
  pgnetwork:
    driver: bridge
