version: '3.1'

services:
  postgres:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: teste
      POSTGRES_DB: curso-api-rest-spring
    ports:
      - 5432:5432
    networks:
      - pgnetwork

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: teste
    ports:
      - 5000:80
    depends_on:
      - postgres
    networks:
      - pgnetwork

networks:
  pgnetwork:
    driver: bridge
